#!/bin/sh
set -e
# I like MzScheme for its diagnostics:
# : ${refscheme:="mzscheme -r"}
# But ELK is the fastest of bigloo, guile, mzscheme, SCM, and ELK for
# this purpose:
: ${refscheme:="elk -l"}
trap '/bin/rm -f refscheme.out newcompiler.out runtest.s runtest' EXIT
runtest () {
        prog="${1?runtest needs an argument}"
        echo "running $prog"
        $refscheme "$prog" > refscheme.out
        $refscheme compiler.scm < "$prog" > runtest.s
        gcc -nostdlib runtest.s -o runtest
        ./runtest > newcompiler.out
        diff -au refscheme.out newcompiler.out
}
for test in test.*.scm; do runtest "$test"; done
