;;; Test the equal? predicate.

(define (try a b) (display (if (equal? a b) " - equal" " - not equal")) (newline))
(try "hi" "bye")
(try "hi" "hi")
(try "hi" (string-append "h" "i"))
(try 'a 'b)
(try 'a 'a)
(try 1 2)
(try 1 1)
(try "a" 1)
(try '() '())
(try '(a b c) (cons 'a '(b c)))
(try '() '(a))
(try '(a) '())
(try '(a) "a")
(try "a" '(a))
(try '(xixaxa xoxaxa) '(xixaxa quuxaxa))
(try '("this" "is" "a" "test") '("this" "is" "a" "mess"))
(try '("this" "is" "a" "test") '("this" "is" "a" "test"))
